<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>Document Title</title>
</head>
<body>
<a href="/tvchat/hijo" target="_blank">Abrir ventana</a>

<script>

    // La ventana hijo me informa que se ha abierto
    function popupAbierto(){
        console.log("Ventana Abierta!!");
    }

    // La ventana hijo me informa que se ha cerrado
    function popupCerrado(){
        console.log("Ventana Cerrada");
    }

</script>
</body>
</html>