<!DOCTYPE html>
<html>
    <head>
        <title>TVChat Demo</title>
        <script src="/js/jquery.marquee.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/jquery-1.7.min.js"></script>
        <script src="/js/jquery.marquee.js" type="text/javascript"></script>
        <script type="application/javascript">

            $(document).ready(function(){

                $('.marquee').marquee();
            });
        </script>
        <!--Tvchat CSS-->
        <link href="/css/tvchat.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="titulo">
            <div class="jugar_izquierda">
                <img src="/img/LogoJugarIzquierdaAnimado.gif">
            </div>
            <div class="logo_afortunado">
                <img src="/img/LogoAfortunadoAnimado.gif">
            </div>
            <div class="jugar_derecha">
                <img src="/img/LogoJugarDerechaAnimado.gif">
            </div>
        </div>
        <div class="luces"></div>
        <div class="interactive">
            <div class="juegos">
            </div>
            <div class="conductora">
            </div>
        </div>
        <div class="tvchat">
            <div id="scroller">
                <div class="static-text"><img src="/img/titulo_tvchat.jpg"></div>
                <div class="static-text"><img src="/img/titulo_tvchat.jpg"></div>
                <div id="ventana" class="marquee">Me gusta tu programa!!_____________________________________Saludos a todos los que me conocen!!!</div>
            </div>
        </div>
    </body>
</html>
