<!DOCTYPE html>
<html>
    <head>
        <title>jQuery marquee test</title>
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script src="//rawgithub.com/tobia/Pause/master/jquery.pause.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" type="text/javascript"></script>
        <script src="/js/jquery.marquee.js" type="text/javascript"></script>
        <script type="application/javascript">
            <!DOCTYPE html>
                <html>
                <head>
                <title>jQuery marquee test</title>
                <!--<link href='../../../../public/css/indexCss.css' rel='stylesheet' type='text/css'>
                <script src="../../../../public/js/jquery-2.1.0.js" type="text/javascript"></script>
        <script src="../../../../public/js/jquery.marquee.min.js" type="text/javascript"></script>
        <script src="../../../../public/js/wrapperJQueryMarquee.js" type="text/javascript"></script>-->
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script src="//rawgithub.com/tobia/Pause/master/jquery.pause.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" type="text/javascript"></script>
        <script src="../../../../js/jquery.marquee.js" type="text/javascript"></script>
        <style type="text/css">
            body {
                margin: 10px;
                font-family: 'Lato', sans-serif;
            }
            small {
                font-size: 14px;
            }
            h1 {
                margin-bottom: 20px;
                padding-bottom: 10px;
                text-align: center;
            }
            h2 {
                border-bottom: 1px dotted #ccc;
                padding-bottom: 5px;
                margin-bottom: 10px;
            }
            .marquee,
            .marquee-with-options,
            .marquee-vert-before,
            .marquee-vert {
                width: 800px;
                overflow: hidden;
                border:1px solid #ccc;
            }
            #ventana {
                background-color: #00b6ff;
                color: #ffffff;
                font-size: 18px;
                height: 28px !important;
                line-height:28px;
                overflow: hidden;
                position: relative;
                width: 1005;
                padding-top: 1px;
                position: relative;
            }
            .scrollingtext {
                color: #ffffff;
                white-space:nowrap;
                position:absolute;
                font-size: 14px;
                font-style: oblique;
            }
            .scrollingtext a:link, .scrollingtext a:visited {
                color: #ffffff;
                font-size: 14px;
            }
            .scrollingtext a:visited {
                text-decoration:none;
            }
            .review {
                padding-right: 50px;
            }
            #static-text {
                position: absolute;
                padding: 0 10px;
                background-color: #00b6ff;
                z-index: 99999;
                font-weight: bold;
            }
            #cargar_normal{

                width: 400px;
            }
        </style>
        <script type="application/javascript">

            var textarray;

            function obtenerMensajesNuevos(){

                textarray = window.opener.obtenerMensajesNuevos();
            }

            $(document).ready(function(){

                function mostrarMensajesMarquee() {

                    var length = textarray.length;
                    console.log(textarray);
                    console.log(textarray.length);
                    if( textarray.length == 0 ){
                        var eliminar = $( '.js-marquee-wrapper' );
                        eliminar.remove();
                        obtenerMensajesNuevos();
                        console.log( textarray );
                        mostrarMensajesMarquee();
                        //return;
                    }
                    var texto = textarray.pop();
                    $mwo
                        .marquee('destroy')
                        .bind('finished', mostrarMensajesMarquee)
                        .html(texto)
                        .marquee({duration: 7000, duplicated:false});
                }

                var $mwo = $('.marquee-with-options');
                var cadena = '';

                $('.marquee-with-options').marquee({
                    //speed in milliseconds of the marquee
                    speed: 10000,
                    //gap in pixels between the tickers
                    gap: 50,
                    //time in milliseconds before the marquee will start animating
                    delayBeforeStart: 0,
                    //'left' or 'right'
                    direction: 'left',
                    //true or false - should the marquee be duplicated to show an effect of continues flow
                    duplicated: false,
                    //on hover pause the marquee - using jQuery plugin https://github.com/tobia/Pause
                    pauseOnHover: true
                });

                $('.iniciar').click(function(e){
                    mostrarMensajesMarquee();
                })
                .click(function(e){
                    e.preventDefault();
                })
                //pause and resume links
                $('.pause').click(function(e){
                    e.preventDefault();
                    //$mwo.trigger('pause');
                    var eliminar = $('.js-marquee-wrapper');
                    eliminar.remove();
                    $mwo.marquee('destroy');
                });

                obtenerMensajesNuevos();
            });
        </script>
    </head>
    <body>
        <div id="ventana" class='marquee-with-options'></div>
        <a class='iniciar' href='#'>Iniciar</a> | <a class='pause' href='#'>Pausa</a>
        <br/><br/>
    </body>
</html>
