<!DOCTYPE html>
<html>
    <head>
        <title>jQuery marquee test</title>
        <!--<link href='../../../../public/css/indexCss.css' rel='stylesheet' type='text/css'>
        <script src="../../../../public/js/jquery-2.1.0.js" type="text/javascript"></script>
        <script src="../../../../public/js/jquery.marquee.min.js" type="text/javascript"></script>
        <script src="../../../../public/js/wrapperJQueryMarquee.js" type="text/javascript"></script>-->
        <!--<script src="js/jquery.marquee.js" type="text/javascript"></script>-->
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script src="//rawgithub.com/tobia/Pause/master/jquery.pause.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" type="text/javascript"></script>
<!--        <script type='text/javascript' src='https://rawgithub.com/aamirafridi/jQuery.Marquee/master/jquery.marquee.min.js'></script>-->
        <script src="/js/jquery.marquee.js" type="text/javascript"></script>
        <script type="application/javascript">
            <!DOCTYPE html>
                <html>
                <head>
                <title>jQuery marquee test</title>
                <!--<link href='../../../../public/css/indexCss.css' rel='stylesheet' type='text/css'>
                <script src="../../../../public/js/jquery-2.1.0.js" type="text/javascript"></script>
        <script src="/js/jquery.marquee.min.js" type="text/javascript"></script>
        <script src="/js/wrapperJQueryMarquee.js" type="text/javascript"></script>-->
        <!--<script src="js/jquery.marquee.js" type="text/javascript"></script>-->
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script src="//rawgithub.com/tobia/Pause/master/jquery.pause.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" type="text/javascript"></script>
        <!--        <script type='text/javascript' src='https://rawgithub.com/aamirafridi/jQuery.Marquee/master/jquery.marquee.min.js'></script>-->
        <script src="/js/jquery.marquee.js" type="text/javascript"></script>
        <style type="text/css">
            body {
                margin: 10px;
                font-family: 'Lato', sans-serif;
            }
            small {
                font-size: 14px;
            }
            h1 {
                margin-bottom: 20px;
                padding-bottom: 10px;
                text-align: center;
            }

            h2 {
                border-bottom: 1px dotted #ccc;
                padding-bottom: 5px;
                margin-bottom: 10px;
            }

            .marquee,
            .marquee-with-options,
            .marquee-vert-before,
            .marquee-vert {
                width: 800px;
                overflow: hidden;
                border:1px solid #ccc;
            }

            #ventana {
                background-color: #00b6ff;
                color: #ffffff;
                font-size: 18px;
                height: 28px !important;
                line-height:28px;
                overflow: hidden;
                position: relative;
                width: 1005;
                padding-top: 1px;
                position: relative;
            }
            .scrollingtext {
                color: #ffffff;
                white-space:nowrap;
                position:absolute;
                font-size: 14px;
                font-style: oblique;
            }
            .scrollingtext a:link, .scrollingtext a:visited {
                color: #ffffff;
                font-size: 14px;
            }
            .scrollingtext a:visited {
                text-decoration:none;
            }

            .review {
                padding-right: 50px;
            }

            #static-text {
                position: absolute;
                padding: 0 10px;
                background-color: #00b6ff;
                z-index: 99999;
                font-weight: bold;
            }

            #cargar_normal{

                width: 400px;
            }
        </style>
        <script type="application/javascript">
            //variables globales
            var mensajes = [];
            var marquesina;
            var siguiente_id_solicitar = 10;
            var mensajes_nuevos = [];

            function obtenerMensajesNuevos(){

                console.log("obtener nuevos mensajes");
                console.log(mensajes);
                return mensajes;
            }

            function cargarMensajes(respuesta){
                $("#mensajes_nuevos_obtenidos").html("Mensajes Nuevos: " + respuesta.mensajes_marquee);
                mensajes.push(respuesta.mensajes_marquee);
                siguiente_id_solicitar = respuesta.siguiente_id_solicitar;
                console.log(mensajes);
                if (respuesta.tieneiva=="1"){
                    $("#mensajes_nuevos_obtenidos").css("background-color", "#ffcc00");
                }else{
                    $("#mensajes_nuevos_obtenidos").css("background-color", "#cc00ff");
                }
            }

            function obtenerMensajesBD(){

                console.log("llamada ajax");
                $.get("http://www.entermovil.com.py.localserver/tvchat/obtener-mensajes", {solicitud: true, id_mensaje:siguiente_id_solicitar}, cargarMensajes, "json");
                return;
            }

            //modulo de obtencion de mensajes
            setInterval(obtenerMensajesBD(), 5000);

            setInterval( mostrarConsultaInterval ,5000);

            var mostrarConsultaInterval = function(){
                MostrarConsulta('consulta_home.php');
                return false;
            }

            $(document).ready(function(){

                $('#abrir_ventana').click(function(){

                    marquesina = window.open("/tvchat/marquee",
                        "_blank", "width=1000, height=70, menubar=no, toolbar=no, location=no, status=yes");
                })

                $("#cargar_mensajes_nuevos").click(function(){
                    obtenerMensajesBD();
                })

                $('#cerrar_ventana').click(function(){
                    marquesina.close();
                })

                $('#cargar').click(function(){
                    var nuevo_mensaje = $('#cargar_normal').val();
                    mensajes.push(nuevo_mensaje);
                    console.log(mensajes);
                })

            });

        </script>

    </head>
    <body>
        <h1>TV Chat</h1>
        <div></div>
        <button id="abrir_ventana">Iniciar</button>
        <button id="cerrar_ventana">Cerrar</button>
        <button id="cargar_mensajes_nuevos">Cargar Mensajes</button>
        <p id="mensajes_nuevos_obtenidos"></p>
        <div>
            <input id="cargar_normal" type="text" value="">
            <a href="#" id="cargar">Cargar</a>
        </div>
    </body>
</html>
