<!DOCTYPE html>
<html>
    <head>
        <title>TVChat</title>
        <script src="/js/jquery-2.1.1.js"></script>
        <script src="/js/tvchat.manager.js" type="application/javascript"></script>
        <script src="/js/tvchat.marquee.manager.js" type="application/javascript"></script>
        <style type="text/css">
            div{
                position: relative;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div>
            <p>
                <h1>Manager</h1>
            </p>
            <p>
                <button id="abrir_ventana">Iniciar</button>
                <button id="cerrar_ventana">Cerrar</button>
            </p>
            <p>
                <button id="cargar_tombola">Tombola</button>
                <button id="cerrar_tombola">Quitar</button>
            </p>
            <p>
                <button id="cargar_tragamonedas">Tragamonedas</button>
                <button id="cerrar_tragamonedas">Quitar</button>
            </p>
            <p>
                <button id="cargar_tvchat">TVchat</button>
                <button id="cerrar_tvchat">Quitar</button>
            </p>
        </div>
        <div>
            <input id="cargar_normal" type="text" value="">
            <a href="#" id="cargar">Cargar</a>
        </div>
    </body>
</html>
