<!DOCTYPE html>
    <html>
    <head>
        <title>TVChat Demo</title>
        <link href="/css/tvchat_demo.css" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="/js/jquery-1.7.min.js"></script>
        <script type="text/javascript" src="/js/tvchat.child.js"></script>
        <script type="text/javascript" src="/js/tvchat.utils.js"></script>
        <script type="text/javascript" src="/js/tvchat.wheel.js"></script>
    </head>
    <body>
        <div class="titulo">
            <h1>Tittle</h1>
        </div>
        <div id="juego" class="juegos">
            <div id="game_wrapper"></div>
        </div>
        <div class="tvchat">
            <h1>Marquee</h1>
        </div>
    </body>
</html>
